### ISSUE TITLE
Question: how to sponsor this project?

### ISSUE THREAD

**Issue by marcelosousa** [dukex/mixpanel#11]
Hi 👋 , 

Thanks so much for the work on this project! At @Reviewpad, we are trying to support the OSS projects that we use as dependencies to our main repository [reviewpad/reviewpad](https://github.com/reviewpad/reviewpad). 

Do you plan to join any sponsoring program? We are also happy to help the community to maintain the project.

Thanks!

**Comment by dukex** [comment]
Hi @marcelosousa, nice to know, you be awesome any help, I just created a liberapay, https://liberapay.com/dukex

**Comment by marcelosousa** [comment]
Hi @dukex . When I try to pledge, it says:

> Cannot be renewed because the account of the recipient isn't ready to receive new payments.

Let me know when this is available!

**Comment by dukex** [comment]
@marcelosousa Done!

**Comment by dukex** [comment]
My GitHub sponsor profile was approved https://github.com/sponsors/dukex

**Comment by marcelosousa** [comment]
Done @dukex ! Enjoy and thanks for the open source contribution!
